"""
CDSCO-format pharmacovigilance report generator.
Generates structured reports ready for regulatory review.
"""
from datetime import datetime
from typing import Dict, List


def generate_pv_report(signal: Dict, project: Dict, posts: List[Dict]) -> Dict:
    now = datetime.utcnow()

    report = {
        "report_metadata": {
            "report_id": f"PV-{now.strftime('%Y%m%d')}-{signal['id']:04d}",
            "report_type": "Individual Case Safety Report (ICSR) - Aggregate",
            "report_date": now.strftime("%Y-%m-%d"),
            "report_version": "1.0",
            "generated_by": "PharmaSentinel Automated Detection System",
            "regulatory_authority": "Central Drugs Standard Control Organisation (CDSCO)",
            "status": "Draft — Pending Review",
            "confidentiality": "RESTRICTED"
        },
        "drug_information": {
            "drug_name": signal["drug_name"].capitalize(),
            "drug_class": project.get("drug_class", ""),
            "brand_names_india": project.get("brand_names", []),
            "cdsco_approval_year": project.get("cdsco_approval", ""),
            "monitoring_project": project["name"],
        },
        "adverse_drug_reaction": {
            "adr_term": signal["adr_term"].upper(),
            "adr_category": signal.get("adr_category", ""),
            "meddra_term": signal["adr_term"].title(),
            "listed_on_cdsco_label": signal["is_on_label"],
            "label_status": "KNOWN" if signal["is_on_label"] else "UNLISTED — POTENTIAL NEW SIGNAL",
            "seriousness": _assess_seriousness(signal),
            "outcome": "Unknown — ongoing monitoring",
        },
        "signal_statistics": {
            "total_reports": signal["report_count"],
            "unique_sources": signal.get("unique_sources", signal["report_count"]),
            "data_sources": ["Reddit", "Twitter/X"],
            "monitoring_period": {
                "start": signal["first_detected"],
                "end": signal["last_updated"],
            },
            "geographic_distribution": signal.get("locations", []),
            "prr_score": signal["prr_score"],
            "prr_interpretation": _interpret_prr(signal["prr_score"]),
            "confidence_score": f"{round(signal['confidence'] * 100)}%",
            "weekly_growth_rate": f"{signal.get('growth_rate', 0)}%",
            "signal_threshold_met": signal["prr_score"] >= 2.0 and signal["report_count"] >= 3,
        },
        "source_reports_summary": _summarize_posts(posts),
        "regulatory_assessment": {
            "priority_level": signal["priority"],
            "recommendation": _get_recommendation(signal),
            "action_required": signal["priority"] == "HIGH" and not signal["is_on_label"],
            "suggested_actions": _get_suggested_actions(signal),
        },
        "pii_compliance": {
            "pii_detection_applied": True,
            "anonymization_method": "SHA-256 hash for author IDs, regex-based PII removal",
            "data_minimization": True,
            "gdpr_compliant": True,
        },
        "footer": {
            "disclaimer": "This report was auto-generated by PharmaSentinel for initial review. All signals must be clinically reviewed by a qualified pharmacovigilance professional before regulatory submission.",
            "next_steps": "Review source posts, confirm clinical plausibility, submit via PvPI portal if validated.",
            "pvpi_contact": "pvpi@cdsco.gov.in",
            "cdsco_portal": "https://pvpi.nic.in",
        }
    }

    return report


def _assess_seriousness(signal: Dict) -> str:
    serious_categories = ["cardiac", "neurological", "hepatic", "renal", "allergic", "hematological"]
    if signal.get("adr_category") in serious_categories:
        return "SERIOUS"
    if signal["report_count"] >= 15 or signal["prr_score"] >= 5:
        return "SERIOUS"
    if signal["priority"] == "HIGH":
        return "POTENTIALLY SERIOUS"
    return "NON-SERIOUS"


def _interpret_prr(prr: float) -> str:
    if prr >= 5.0:
        return f"PRR = {prr} — Strong signal (>5x background rate)"
    elif prr >= 2.0:
        return f"PRR = {prr} — Positive signal (>2x background rate, meets WHO threshold)"
    elif prr >= 1.5:
        return f"PRR = {prr} — Weak signal (1.5–2x background rate)"
    else:
        return f"PRR = {prr} — No signal detected"


def _get_recommendation(signal: Dict) -> str:
    if not signal["is_on_label"] and signal["priority"] == "HIGH":
        return "URGENT: Possible unlisted adverse drug reaction detected. Clinical review and potential label update required."
    elif not signal["is_on_label"] and signal["priority"] == "MEDIUM":
        return "Potential unlisted adverse reaction. Requires further monitoring and clinical assessment."
    else:
        return "Known side effect. Continue standard pharmacovigilance monitoring."


def _get_suggested_actions(signal: Dict) -> List[str]:
    actions = []
    if not signal["is_on_label"]:
        actions.append("Review all source posts for clinical plausibility")
        actions.append("Consult clinical pharmacologist for causality assessment")
        actions.append("Cross-reference with WHO VigiBase for global reports")
        if signal["priority"] == "HIGH":
            actions.append("Consider issuing Dear Healthcare Professional letter")
            actions.append("Evaluate need for CDSCO label update via Form 69")
            actions.append("Submit signal to PvPI (Pharmacovigilance Programme of India)")
    else:
        actions.append("Log as expected ADR in pharmacovigilance database")
        actions.append("Monitor for any increase in severity or frequency")
    return actions


def _summarize_posts(posts: List[Dict]) -> List[Dict]:
    summary = []
    for i, post in enumerate(posts[:5], 1):
        summary.append({
            "case_number": f"CASE-{i:03d}",
            "source_platform": post.get("source", "reddit").upper(),
            "community": post.get("subreddit", "N/A"),
            "post_date": post.get("posted_at", ""),
            "reported_location": post.get("location", "India"),
            "anonymized_excerpt": _get_excerpt(post.get("anonymized_content") or post.get("content", ""), 200),
            "extracted_adrs": [a["term"] if isinstance(a, dict) else a
                               for a in post.get("extracted_adrs", [])],
            "confidence_score": post.get("confidence_score", 0),
            "author_id": post.get("author_hash", "ANON"),
        })
    return summary


def _get_excerpt(text: str, max_len: int) -> str:
    if len(text) <= max_len:
        return text
    return text[:max_len].rsplit(" ", 1)[0] + "..."
